# Use Node.js base image
FROM node:16

# Set the working directory
WORKDIR /frontend

# Copy the frontend files to the container
COPY . /frontend


# Install dependencies
RUN npm install

# Expose the port for React
EXPOSE 3000

# Run the React application
CMD ["npm", "start"]
